### ISSUE TITLE
Event: Change the type of eventId

### ISSUE THREAD

**Issue by austin-16** [CMPUT301W24T37/QuantumScan#48]
Event: change the type of the Event ID from "int" to "String"? To keep consistent with userid's type (which is String)
any thoughts?
(I didn't find the primary key for the Event in Firebase)

**Comment by austin-16** [comment]
Since eventID will probably be random_id+user_id, I will change it to String

**Comment by weiz0123** [comment]
If we keep this way, it will be easier to manage id when it comes to implement methods in the code. ( dont have to keep track of data type in our brain(s) :)
