### ISSUE TITLE
User: delete US 03.03.x?

### ISSUE THREAD

**Issue by austin-16** [CMPUT301W24T37/QuantumScan#50]
title
we don't need this system anymore, so how about we removing these US?

> US 03.03.01 As a user, I want to be able to sign up an account
US 03.03.02 As a user, I want to be able to login in an account
US 03.03.03 As a user, I want to be able to find my password back if I forget my password of the account

**Comment by weiz0123** [comment]
yes, we can remove these. we just need to auto-athorize the user now

**Comment by austin-16** [comment]
removed.
